### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by Elenore1997** [iris2hu/L2C-rater#1]
Hi, I am interesting in your work and have a question about the dataset used in your paper. I went to the website  (http://hsk.blcu.edu.cn/) and found that it can be downloaded 500 essays randomly. So I want to ask that how to access to the same dataset used in your paper. Thanks in advance!

**Comment by iris2hu** [comment]
Yes, the corpus website has a download limit, and we don't have the copyright to release or publish the dataset. It is suggested to contact the corpus developer, or visit the essays one by one on "全篇检索" page with an automatic browser interaction tool e.g. Selenium.
