### ISSUE TITLE
Question about how to reproduce the experimental results

### ISSUE THREAD

**Issue by Lingeng56** [iris2hu/L2C-rater#3]
Hi, I am very interested in your work. And I think your work is very nice and try to reproduce the results which are in the paper. And I found the features selected after step-wise regression with default hyper-params are different from those in paper, I got 29 but the paper reports 33. And in the code, I didn't see anything about writing-error features which are also mentioned in your work. 

- For Feature Selection: I think maybe the hyper-parameters are different from the ones you used in your experiment, so if it is convenient, maybe you provide the parameters used in the experiment to me.
- For Writing-Error Features: I am not sure whether I missed it in your code or I should use some methods like statistics to create them.
：）

**Comment by iris2hu** [comment]
Hi, please see the attached file and the following tips for reproducing the experimental results:

# hsk.log
- The results of five-fold cross validation. The mean scores of five-fold are reported in our paper.

# group_id.json
- The train/valid/test essay ID used in the five-fold experiments .

# [***IMPORTANT***] features_essay_revised_v1.csv 
- The 90 linguistic and 5 writting error features, which can be used directly in reproducing the experiments, particularly when you do not have access to the whole corpus.
- The 90 linguistic features are automatically extracted using the codes, and the 5 writting error features are computed based the annotation of the L2 corpus (see in the paper Section 3.1). 

# [***IMPORTANT***] feature_name.json
- The feature list in Appendix A, which was selected with the SPSS stepwise regression module.
- When building the open-source project, we implemented an feature selection in Python and hoped that this process can be done automatically in future (without manual work in SPSS). Note that the features selected from Python-based step-wise regression are not exactly the same as the ones from SPSS.
- For reproducing the experiments, this feature list (Appendix A) should be directly used. If going for further research, it is more suggested to use the Python-based feature selection module.

[l2c-rater_reproduce_memo.zip](https://github.com/iris2hu/L2C-rater/files/7955153/l2c-rater_reproduce_memo.zip)

**Comment by YpLarryWang** [comment]
> Hi, I am very interested in your work. And I think your work is very nice and try to reproduce the results which are in the paper. And I found the features selected after step-wise regression with default hyper-params are different from those in paper, I got 29 but the paper reports 33. And in the code, I didn't see anything about writing-error features which are also mentioned in your work.
> 
> * For Feature Selection: I think maybe the hyper-parameters are different from the ones you used in your experiment, so if it is convenient, maybe you provide the parameters used in the experiment to me.
> * For Writing-Error Features: I am not sure whether I missed it in your code or I should use some methods like statistics to create them.
>   ：）

Hi, glad to know that you are interested in our work. Regarding the inconsistency you mentioned between the features selected by stepwise regression and the features listed in the original paper, I have some updates here. 

By the time you raised this issue, the result given by the python code for feature selection was unstable, that is, if you run it multiple times, you will get different selection results. Currently, this bug has been fixed. If you are concerned about this, you can refer to the [latest stepwise regression code](https://github.com/iris2hu/L2C-rater/blob/main/stepwise_selection.py).

**NOTE** the features selected by the code provided here are still different from those selected by SPSS. Only instability have been resolved.
