### ISSUE TITLE
How to use this application please ?

### ISSUE THREAD

**Issue by higkoo** [iris2hu/L2C-rater#4]
- evn:  Linux Debian9 4.9.267 /  Python 3.6.3
-  unzip http://model.scir.yunfutech.com/model/ltp_data_v3.4.0.zip to ltp_models
- python3.7 main.py -m b -t wp -dp data/
- Result is data/essay_linguistic_indices.csv
![image](https://user-images.githubusercontent.com/3828931/192263741-4c097e53-8d8b-4fe7-9b7f-357fd40392f9.png)
Then ?

**Comment by YpLarryWang** [comment]
Hi, thanks for your interest in our research and sorry for the delay.
What your screenshot shows is the normal process in the calculation of the program. The reason for a series of warnings is that the amount of data is too small, and the algorithm results may be unstable. You can first check whether the log is normal. If it is normal, you can consider adding more data, or migrating linguistic features to other application scenarios.
Hope that helps!
